[tool.black]
line-length = 100

[tool.isort]
profile = "black"
force_sort_within_sections = true
line_length = 100
default_section = "THIRDPARTY"
src_paths = ["geometry-mechanical-dpf", "geometry-mesh-fluent", "geometry-mesh"]
